// Generated by scripts/sync-post-metadata.mjs. Do not edit by hand.
export const postWordCounts = {
    "30-days-of-ai": 877,
    "baseline-can-be-the-result": 296,
    "data-products-need-honesty": 181,
    "designing-for-the-fallback": 192,
    "past-papers-need-a-pipeline": 323,
    "patterns-to-practice-2025": 302,
    "prediction-needs-context": 289,
    "shazam-clone": 385,
    "shipping-is-a-design-decision": 187,
    "smallest-useful-version": 167,
    "study-progress-that-survives-refresh": 348,
};
