// Generated by scripts/sync-post-metadata.mjs. Do not edit by hand.
export const postWordCounts = {
    "30-days-of-ai": 877,
    "data-products-need-honesty": 181,
    "designing-for-the-fallback": 192,
    "shazam-clone": 392,
    "shipping-is-a-design-decision": 187,
    "smallest-useful-version": 167,
};
